# Workflow untuk membangun NetQ, mengenkripsi, dan kemudian menerapkan ke GitHub Pages
name: Build Dropbear

on:
  # Berjalan saat push ke branch default
  push:
    branches:
      - main

  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Set izin GITHUB_TOKEN untuk menerapkan ke GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  # Job membangun NetQ
  build_netq:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Dropbear
        working-directory: ./
        run: |
          sudo apt-get install libz-dev -y
          ./configure
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" install
          make install DESTDIR=rilis
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build NetQ
