# Workflow untuk membangun NetQ, mengenkripsi, dan kemudian menerapkan ke GitHub Pages
name: Build Dropbear

on:
  # Berjalan saat push ke branch default
  push:
    branches:
      - main

  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Set izin GITHUB_TOKEN untuk menerapkan ke GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Job membangun NetQ menggunakan matrix
  build_netq:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [amd64, arm64]  # Menambahkan platform yang akan dibangun

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libz-dev -y

      - name: Build for ${{ matrix.arch }}
        env:
          GOARCH: ${{ matrix.arch }}  # Menyesuaikan arsitektur sesuai dengan matrix
        run: |
          mkdir -p rilis/bin-${{ matrix.arch }}
          ./configure
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" install
          mv dropbear dbclient dropbearkey dropbearconvert scp rilis/bin-${{ matrix.arch }}/
          cd rilis/bin-${{ matrix.arch }}
          # Menghapus file lama jika ada
          rm -f dropbear_rsa_host_key dropbear_dss_host_key
          ./dropbearkey -t rsa -f dropbear_rsa_host_key
          ./dropbearkey -t dss -f dropbear_dss_host_key

      - name: Pull latest changes from origin/main
        run: |
          git pull origin main

      - name: Commit and Push Binaries
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build NetQ for ${{ matrix.arch }}
